ERROR:root:division by zero
Traceback (most recent call last):
  File "E:/1a_MyFile/pyFiles/test_5/exceptions1.py", line 43, in main
    bar('0')
  File "E:/1a_MyFile/pyFiles/test_5/exceptions1.py", line 39, in bar
    return foo(s) * 2
  File "E:/1a_MyFile/pyFiles/test_5/exceptions1.py", line 36, in foo
    return 10 / int(s)
ZeroDivisionError: division by zero
ERROR:root:division by zero
Traceback (most recent call last):
  File "E:/1a_MyFile/pyFiles/test_5/exceptions1.py", line 55, in main
    bar('0')
  File "E:/1a_MyFile/pyFiles/test_5/exceptions1.py", line 51, in bar
    return foo(s) * 2
  File "E:/1a_MyFile/pyFiles/test_5/exceptions1.py", line 48, in foo
    return 10 / int(s)
ZeroDivisionError: division by zero
